import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NextAuthSessionProvider from "@/components/SessionProvider";
import ThemeProvider from "@/components/ThemeProvider";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

import QueryProvider from "@/components/QueryProvider";


const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={` ${inter.className} grid place-items-center transition-all`}
      >
        <NextAuthSessionProvider>
        <QueryProvider>
        
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <main className="max-w-screen-2xl md:min-w-[1280px] ">
              <Navbar />
              {children}
              <Footer />
            </main>
          </ThemeProvider>
          </QueryProvider>
          
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
